openapi: "3.0.0"

info:
  title: "bookmanager"
  version: "0.0.1"
  description: "This is draft version."
servers:
  - url: "http://localhost:5000"
    description: "Flask"

tags:
  - name: "user"
  - name: "book"
  - name: "record"
paths:
  /user/{username}:
    get:
      summary: "読了数"
      description: "return number of read/reading/unread/wish books"
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "ok"
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  read:
                    type: integer
                  reading:
                    type: integer
                  unread:
                    type: integer
                  wish:
                    type: integer
      tags:
        - "user"

  /book/{isbn}:
    get:
      summary: "書籍情報"
      description: ""
      tags:
        - "book"
      parameters:
        - name: isbn
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "ok"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isbn:
                    type: string
                  title:
                    type: string
                  author:
                    type: string
                  publisher:
                    type: string

  /record:
    post:
      summary: "記録する"
      tags:
        - "record"
      # parameters:
      #   - name: userid
      #     in: path
      #     required: true
      #     schema:
      #       type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                status:
                  type: string
                  description: "read or reading or unread or wish"
                # record_at:
                #   type: string
                #   format: "date-time"
                #   description: "更新日時(ISO-8601)，指定なければサーバータイム"
                isbn:
                  type: string
                  description: "ISBN"
                # note:
                #   description: メモ
                #   type: string
      responses:
        "200":
          description: "ok"
  /user/{username}/{isbn}:
    get:
      tags:
        - "user"
      summary: 特定の本の読了記録を取得する
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: isbn
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "ok"
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  isbn:
                    type: string
                  status:
                    type: string
                  record_at: 
                    type: string
                    format: "date-time"